name: Build and push images
on:
  #the job is launched from the test_backend workflow
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  build-and-push-database:
    needs: test-backend
    runs-on: ubuntu-latest
    env:
      working-directory: ./Database
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Database
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/my-database:latest
          push: ${{ github.ref == 'refs/heads/master' }}

  build-and-push-simple-api:
    needs: test-backend
    runs-on: ubuntu-latest
    env:
      working-directory: ./API/simple-api
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:

          # relative path to the place where source code with Dockerfile is located
          context: ./API/simple-api
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/simple-api:latest
          push: ${{ github.ref == 'refs/heads/master' }}

  
  build-and-push-http-server:
    needs: test-backend
    runs-on: ubuntu-latest
    env:
      working-directory: ./HTTP server
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./HTTP server
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/http:latest
          push: ${{ github.ref == 'refs/heads/master' }}
  
  build-and-push-front:
    runs-on: ubuntu-18.04
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image and push front
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./devops-front-main
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/front:latest
          push: ${{ github.ref == 'refs/heads/master' }}